test: add unit tests for `slurm_ops`
charmed-hpc/hpc-libs pull request #3
Opened 2024-07-01 23:53 UTC by jedel1043

A bit of magic on the test file to avoid having to repeat 4 times the exact same test code, but I think we can live with that 😬

2024-07-02 21:08 UTC, NucciTheBoss requested changes
Overall, looks great! Just a couple minor comments.

Before we merge, can you also add some coverage for lines 89-92? It's the block for handling if the subprocess invocation in `_call` fails. Not too difficult to add a side effect for `subprocess.check_output(...)`. I want to have this block covered just so we know that the error is properly bubbled up, and it is nice to have the groundwork laid for testing any advanced error recovery mechanisms we might add. Also, who doesn't love 100% coverage :stuck_out_tongue_winking_eye: 

Let me know if you have any questions!

2024-07-02 21:10 UTC, NucciTheBoss commented
> A bit of magic on the test file to avoid having to repeat 4 times the exact same test code, but I think we can live with that 😬

I can live with it :rofl:

2024-07-02 21:27 UTC, jedel1043 commented on tests/unit/test_slurm_ops.py
> +    )
Because we're also testing that the config_name for the services is correct, and that must come from an external source.

2024-07-03 13:32 UTC, NucciTheBoss approved these changes
LGTM! Thanks for adding that last bit of coverage :smiley:

2024-07-03 13:32 UTC, NucciTheBoss commented on tests/unit/test_slurm_ops.py
> +    )
Ah, so it's like a table test then where index 1 of the tuple is the expected output. Got it :smiley:

2024-07-03 13:32 UTC, merged