feat!: use composition and inheritance to build service managers
charmed-hpc/hpc-libs pull request #8
Opened 2024-07-09 21:19 UTC by NucciTheBoss

This pull request enhances the API of `slurm_ops` to use composition and inheritance to build the Slurm service operations managers. This makes it easier for us to construct managers around `slurmctld`, `slurmd`, `slurmdbd`, and `slurmrestd` and share logic for configuration and service management between them. 

### Some use cases

bulk update the configuration of slurmctld:

```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType

slurmctld = SlurmManagerBase(ServiceType.SLURMCTLD)
slurmctld.config.set({"option1": "value1", "option2": "value2"})
```

set a new munge key:

```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType

slurmd = SlurmManagerBase(ServiceType.SLURMD)
slurmd.munge.set_key("encodedmungekey")
slurmd.munge.restart()
```

start slurmrestd:

```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType

slurmrestd = SlurmManagerBase(ServiceType.SLURMRESTD)
slurmrestd.enable()
```

add additional, charm-specific functionality:

```python3
from charms.hpc_libs.v0.slurm_ops import SlurmManagerBase, ServiceType

class SlurmdbdManager(SlurmManagerBase)

    def __init__(self) -> None:
        super().__init__(ServiceType.SLURMCTLD)

        # Compose additional manager functionality.
        self.cgroup = ...
```

### Misc.

Adds kebabizer from @jedel1043. The function `format_key(...)` will be used to format Slurm configuration keys before passing off to the Slurm configuration editor.

2024-07-09 21:42 UTC, jedel1043 requested changes
Looks great! I just have some questions around needing `Pyfakefs`.

2024-07-09 21:42 UTC, jedel1043 commented on lib/charms/hpc_libs/v0/slurm_ops.py
> +       become `cp-us` if put through a kebabizer with being preformatted to `Cpus`.
Praise: love the clarity of the docs!

2024-07-09 21:42 UTC, jedel1043 commented on tests/unit/test_slurm_ops.py
>          self.setUpPyfakefs()
I don't think this is used here anymore.

2024-07-09 21:42 UTC, jedel1043 commented on tests/unit/test_slurm_ops.py
> +        self.setUpPyfakefs()
Seems like this test also doesn't require Pyfakefs anymore?

2024-07-10 13:39 UTC, NucciTheBoss commented on lib/charms/hpc_libs/v0/slurm_ops.py
> +       become `cp-us` if put through a kebabizer with being preformatted to `Cpus`.
🙇

2024-07-10 13:47 UTC, NucciTheBoss commented
@jedel1043 good catch with `pyfakefs`! Ready for review again :mag_right:

2024-07-10 13:55 UTC, NucciTheBoss commented
> Also, for future reference before we merge, we need to bump the lib patch version so that the updated lib will get published to Charmhub

2024-07-10 14:47 UTC, jedel1043 approved these changes
LGTM!

2024-07-10 15:22 UTC, merged